namespace Chsword.Excel2Object
{
    public enum ExcelStyleColor : short
    {
        //ColorNormal = 32767,
        Black = 8,
        Brown = 60,
        OliveGreen = 59,
        DarkGreen = 58,
        DarkTeal = 56,
        DarkBlue = 18,
        Indigo = 62,
        Grey80Percent = 63,
        Orange = 53,
        DarkYellow = 19,
        Green = 17,
        Teal = 21,
        Blue = 12,
        BlueGrey = 54,
        Grey50Percent = 23,
        Red = 10,
        LightOrange = 52,
        Lime = 50,
        SeaGreen = 57,
        Aqua = 49,
        LightBlue = 48,
        Violet = 20,
        Grey40Percent = 55,
        Pink = 14,
        Gold = 51,
        Yellow = 13,
        BrightGreen = 11,
        Turquoise = 15,
        DarkRed = 16,
        SkyBlue = 40,
        Plum = 61,
        Grey25Percent = 22,
        Rose = 45,
        LightYellow = 43,
        LightGreen = 42,
        LightTurquoise = 41,
        PaleBlue = 44,
        Lavender = 46,
        White = 9,
        CornflowerBlue = 24,
        LemonChiffon = 26,
        Maroon = 25,
        Orchid = 28,
        Coral = 29,
        RoyalBlue = 30,
        LightCornflowerBlue = 31,
        Tan = 47,
    }
}